### ISSUE TITLE
Registration form for get_involved page

### ISSUE THREAD

**Issue by AlbertV11** [Ankurakjain/ESACH#11]
Hello everyone!

I am implementing a registration form for the get_involved page.
Which fields do you need in this form except already added?
![image](https://user-images.githubusercontent.com/47282711/103497580-0babe980-4e53-11eb-9720-91bb31cac351.png)

Thanks,
Albert

**Comment by Ankurakjain** [comment]
You can add Note or Comment section in it.

**Comment by AlbertV11** [comment]
Ok, I have added it.
![image](https://user-images.githubusercontent.com/47282711/103910743-3da0a280-5116-11eb-9407-cc0ed670aa01.png)

**Comment by AlbertV11** [comment]
New(final) version of this form.
![image](https://user-images.githubusercontent.com/47282711/104113884-44ded080-530f-11eb-81eb-b4f8178c00d5.png)
