### ISSUE TITLE
Donation form for donate.html page

### ISSUE THREAD

**Issue by AlbertV11** [Ankurakjain/ESACH#13]
Hello everyone!

I am implementing a donation form for the donate.html page.
Are you satisfied with this page or you need more fields?
![image](https://user-images.githubusercontent.com/47282711/103909394-b0108300-5114-11eb-95d6-1837e809e08d.png)

Thanks,
Albert

**Comment by Ankurakjain** [comment]
Hello Albert, 

I guess, all the fields are fine. No additional fields are required. 

Best regards,
Ankur

**Comment by AlbertV11** [comment]
Ok, so I am closing the issue.
