### ISSUE TITLE
Committee page final version

### ISSUE THREAD

**Issue by AlbertV11** [Ankurakjain/ESACH#14]
Hello everyone!

We have made the final version of the Committee.html page.
Are you satisfied with the design of this page?
![image](https://user-images.githubusercontent.com/47282711/104105772-8d6f9d00-52c1-11eb-9cde-48fcb4f63adb.png)
![image](https://user-images.githubusercontent.com/47282711/104105777-995b5f00-52c1-11eb-8e34-c0a6eca40dd8.png)

Albert

**Comment by Ankurakjain** [comment]
Its good. You can finalize this.

**Comment by AlbertV11** [comment]
Ok, cool!
So this version will be final.
