### ISSUE TITLE
XML file

### ISSUE THREAD

**Issue by tiadal** [Ankurakjain/ESACH#15]
Hello @Ankurakjain hello @adamrinder ,

we are going to finish the XML file, but some data are missing, is there a place where I can get all the info or should I change the XML structure? 
<title>ESACH OPOLE – ESACH</title>
  <speakers>"Example speaker1"</speakers>
  <date>2.12.2020</date>
  <theme>"An example topic"</theme>
  <details>This is the information about the actual event</details>
</event>

Thanks

**Comment by Ankurakjain** [comment]
You should change the XML structure.

**Comment by galois26** [comment]
I agree, please feel free to update the structure to suit your needs.
