### ISSUE TITLE
Supporting_institutes page final version

### ISSUE THREAD

**Issue by AlbertV11** [Ankurakjain/ESACH#17]
Hello everyone!

We have made the final version of the Supporting_institutes.html page.
Are you satisfied with the design of this page?
![image](https://user-images.githubusercontent.com/47282711/104113933-b3239300-530f-11eb-8d27-054f19dc9b91.png)
![image](https://user-images.githubusercontent.com/47282711/104113935-b74fb080-530f-11eb-8d1c-11b7578ee64c.png)

Albert

**Comment by Ankurakjain** [comment]
Yeah, it looks fine.

**Comment by AlbertV11** [comment]
Ok, cool!
