### ISSUE TITLE
Docs/ Folder

### ISSUE THREAD

**Issue by tiadal** [Ankurakjain/ESACH#2]
Hello Group 3, 

could you please set up the docs/ folder as stated in the assignment description: "Create a docs folder in the repo as the root of your Github Pages website, which you have to set up in the Settings tab."

Thanks,
Mattia

**Comment by Ankurakjain** [comment]
Check with the folder, and let me know is that the thing you want or something else :)

**Comment by tiadal** [comment]
Hello Group 3,

I can pull it put I can't push it, please check my rights:
[
<img width="479" alt="Screenshot 2020-12-23 at 11 29 21" src="https://user-images.githubusercontent.com/73166570/102987349-76375e00-4512-11eb-91ba-3b5eff2ed048.png">
](url)

Thanks

**Comment by Ankurakjain** [comment]
I checked with the access and it shows pending. Can you please check your email? 
I think you didn't confirm it. :)

**Comment by tiadal** [comment]
Hello, could you please try to send it again? I can't find the email. Thanks :)

**Comment by Ankurakjain** [comment]
I reissued the access

**Comment by tiadal** [comment]
Yes it worked. Thanks
