### ISSUE TITLE
index.html page changes

### ISSUE THREAD

**Issue by AlbertV11** [Ankurakjain/ESACH#20]
Hello everyone!

We changed the design of index.html page.(We added registration for upcoming events) 
Are you satisfied with these changes?
![image](https://user-images.githubusercontent.com/47282711/104145020-900fe680-53d6-11eb-9daf-3716ae41a0fc.png)

Albert

**Comment by Ankurakjain** [comment]
yes, i am satisfied.

**Comment by AlbertV11** [comment]
Ok, so I am closing the issue.
