### ISSUE TITLE
Missing Content

### ISSUE THREAD

**Issue by tiadal** [Ankurakjain/ESACH#3]
Hello Group3,

The content for the following pages is missing or I could not assign it:

- News (Title - News) --do you need extra content here? Otherwise, the page barely links to 
- Publications (Title - Publications)
- Donate (Title - Donate now)
- Get Involved (Title - Want to Join)

Let us know if we can proceed without and structure the page in another way or if it will be provided

Thanks,
Mattia

**Comment by Ankurakjain** [comment]
For Get involved page, you can check box2 in design folder. Don't need much content there same for Donate page. 
For news page, you can add videos there. and i will upload pdf's for Publications page. 

Is that all right ?

**Comment by tiadal** [comment]
Yes all good

I will close the issue once the files are provided, thanks :)

**Comment by Ankurakjain** [comment]
I added the additional pdf's. Please let me know if anything is missing.

**Comment by Ankurakjain** [comment]
Content is already provided.
