### ISSUE TITLE
FIRST DEMO

### ISSUE THREAD

**Issue by tiadal** [Ankurakjain/ESACH#5]
Hello everyone, 

I created a new branch called "first_demo". There you will find the code for the first design implementation.

**UI/UX**
The goal was to present various design implementations and ideas for the final project. The result is a mix of styles and effects implemented in a fully responsive design. In order not to overwhelm the user and the lack of nice high-res pictures, we went for a less radical style, with lots of white spaces few smaller elements, in order to focus the attention of the user.

The base demo is black and white and it's possible to test other colors by clicking on the  "style-picker" (The circle on the mid-left of the screen). Clicking on the other circles, that will appear, will change the style accordingly. 

**HEADER / MENU**
standard menu with logo on the left and main pages to the right. It will collapse to a hamburger menu on smaller devices. We didn't want to change it much and reinvent the wheel since most users are used to it. We will add a dropdown menu on the final versions.

**PAGE STRUCTURE**
The main structure is either composed of fullscreen sections or longer sections. 
We made use of grids and flexbox in order to make it responsive. 
We can come up with different layouts.

**FOOTER**
- Three main sections, a sticky element with social icon and breadcrumbs
- The actual footer with links to pages, contacts, and small description + logo
- Copyright 

Please check it out and let me know, what and if you like any implementation.

Thanks and have a nice Christmas :)
Mattia

**Comment by tiadal** [comment]
It can be seen here: https://ankurakjain.github.io/ESACH/

**Comment by Ankurakjain** [comment]
The website looks great. I like it but it needs few changes - 
1. In coordination committee, can we have 2 rows 3+2. There are 5 boxes in the same line. It would look good if split in 2 rows.
2. In the News Section, the black line is cutting the Text. Either you can resolve it or may be you can remove that line from news section. For me, both will work. 
3. Regarding color scheme, you can proceed with gray color (first choice).

**Comment by Ankurakjain** [comment]
Hello Mattia,

Merry Christmas to you too!

I like the implementation and everything about it. You took a nice approach and I really appreciate it. You can continue working on this and will see if any further changes required. 

Best regards,
Ankur

**Comment by tiadal** [comment]
Hello Ankur,

thanks for the feedback.

1. I used cards and horizontal scrolling so that there is always one row on both desktop and mobile and the user can scroll left or right in order to see them all. I will put them in one row and have vertical scrolling on mobile devices.
2. I will try to resolve it otherwise I will remove it as you suggested it.
3. Perfect 

Thanks,
Mattia

**Comment by tiadal** [comment]
Hello @Ankurakjain hello @adamrinder 

the demo with all pages and the same style is now online: https://ankurakjain.github.io/ESACH/index.html

Please let me know what would you like to change so that I can start working on the final version.
COLOR, TEXT, IMAGES and VIDEOS are not final and were chosen in order to give you a feeling of a real website.

Thanks,
Mattia

**Comment by Ankurakjain** [comment]
In my view, everything is all right. Even the colors are good. You can stick with it.

**Comment by Ankurakjain** [comment]
No need for this issue now, it is resolved.
